// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DAL.Migrations
{
    [DbContext(typeof(OutdoorContext))]
    partial class OutdoorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AnimalLake", b =>
                {
                    b.Property<int>("AnimalsId")
                        .HasColumnType("int");

                    b.Property<int>("LakesId")
                        .HasColumnType("int");

                    b.HasKey("AnimalsId", "LakesId");

                    b.HasIndex("LakesId");

                    b.ToTable("AnimalLake");
                });

            modelBuilder.Entity("AnimalNatureReserve", b =>
                {
                    b.Property<int>("AnimalId")
                        .HasColumnType("int");

                    b.Property<int>("NatureReservesId")
                        .HasColumnType("int");

                    b.HasKey("AnimalId", "NatureReservesId");

                    b.HasIndex("NatureReservesId");

                    b.ToTable("AnimalNatureReserve");
                });

            modelBuilder.Entity("AnimalPark", b =>
                {
                    b.Property<int>("AnimalsId")
                        .HasColumnType("int");

                    b.Property<int>("ParksId")
                        .HasColumnType("int");

                    b.HasKey("AnimalsId", "ParksId");

                    b.HasIndex("ParksId");

                    b.ToTable("AnimalPark");
                });

            modelBuilder.Entity("Core.Entities.Animal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Type");

                    b.HasKey("Id");

                    b.ToTable("Animal", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Extras", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Extras");
                });

            modelBuilder.Entity("Core.Entities.Outdoor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreateDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("Description");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Image");

                    b.Property<double>("Latitude")
                        .HasColumnType("float")
                        .HasColumnName("Latitude");

                    b.Property<double>("Longitude")
                        .HasColumnType("float")
                        .HasColumnName("Longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Name");

                    b.Property<int>("WorkingHours")
                        .HasColumnType("int")
                        .HasColumnName("WorkingHours");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Outdoor", (string)null);
                });

            modelBuilder.Entity("ExtrasFountain", b =>
                {
                    b.Property<int>("ExtrasId")
                        .HasColumnType("int");

                    b.Property<int>("FountainsId")
                        .HasColumnType("int");

                    b.HasKey("ExtrasId", "FountainsId");

                    b.HasIndex("FountainsId");

                    b.ToTable("ExtrasFountain");
                });

            modelBuilder.Entity("ExtrasLake", b =>
                {
                    b.Property<int>("ExtrasId")
                        .HasColumnType("int");

                    b.Property<int>("LakesId")
                        .HasColumnType("int");

                    b.HasKey("ExtrasId", "LakesId");

                    b.HasIndex("LakesId");

                    b.ToTable("ExtrasLake");
                });

            modelBuilder.Entity("ExtrasLandmark", b =>
                {
                    b.Property<int>("ExtrasId")
                        .HasColumnType("int");

                    b.Property<int>("LandmarksId")
                        .HasColumnType("int");

                    b.HasKey("ExtrasId", "LandmarksId");

                    b.HasIndex("LandmarksId");

                    b.ToTable("ExtrasLandmark");
                });

            modelBuilder.Entity("ExtrasNatureReserve", b =>
                {
                    b.Property<int>("ExtrasId")
                        .HasColumnType("int");

                    b.Property<int>("NatureReservesId")
                        .HasColumnType("int");

                    b.HasKey("ExtrasId", "NatureReservesId");

                    b.HasIndex("NatureReservesId");

                    b.ToTable("ExtrasNatureReserve");
                });

            modelBuilder.Entity("ExtrasPark", b =>
                {
                    b.Property<int>("ExtrasId")
                        .HasColumnType("int");

                    b.Property<int>("ParksId")
                        .HasColumnType("int");

                    b.HasKey("ExtrasId", "ParksId");

                    b.HasIndex("ParksId");

                    b.ToTable("ExtrasPark");
                });

            modelBuilder.Entity("ExtrasVilla", b =>
                {
                    b.Property<int>("ExtrasId")
                        .HasColumnType("int");

                    b.Property<int>("VillasId")
                        .HasColumnType("int");

                    b.HasKey("ExtrasId", "VillasId");

                    b.HasIndex("VillasId");

                    b.ToTable("ExtrasVilla");
                });

            modelBuilder.Entity("Core.Entities.Fountain", b =>
                {
                    b.HasBaseType("Core.Entities.Outdoor");

                    b.Property<string>("InMemoryOf")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("InMemoryOf");

                    b.Property<string>("WaterType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("WaterType");

                    b.ToTable("Fountain", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Lake", b =>
                {
                    b.HasBaseType("Core.Entities.Outdoor");

                    b.ToTable("Lake", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Landmark", b =>
                {
                    b.HasBaseType("Core.Entities.Outdoor");

                    b.ToTable("Landmark", (string)null);
                });

            modelBuilder.Entity("Core.Entities.NatureReserve", b =>
                {
                    b.HasBaseType("Core.Entities.Outdoor");

                    b.Property<double>("Size")
                        .HasColumnType("float")
                        .HasColumnName("Size");

                    b.ToTable("NatureReserve", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Park", b =>
                {
                    b.HasBaseType("Core.Entities.Outdoor");

                    b.Property<string>("Safety")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Safety");

                    b.Property<string>("WalkingPaths")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("WalkingPaths");

                    b.ToTable("Park", (string)null);
                });

            modelBuilder.Entity("Core.Entities.Villa", b =>
                {
                    b.HasBaseType("Core.Entities.Outdoor");

                    b.Property<int>("ParkingCount")
                        .HasColumnType("int")
                        .HasColumnName("ParkingCount");

                    b.Property<int>("RoomCount")
                        .HasMaxLength(10)
                        .HasColumnType("int")
                        .HasColumnName("RoomCount");

                    b.ToTable("Villa", (string)null);
                });

            modelBuilder.Entity("AnimalLake", b =>
                {
                    b.HasOne("Core.Entities.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Lake", null)
                        .WithMany()
                        .HasForeignKey("LakesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimalNatureReserve", b =>
                {
                    b.HasOne("Core.Entities.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.NatureReserve", null)
                        .WithMany()
                        .HasForeignKey("NatureReservesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AnimalPark", b =>
                {
                    b.HasOne("Core.Entities.Animal", null)
                        .WithMany()
                        .HasForeignKey("AnimalsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Park", null)
                        .WithMany()
                        .HasForeignKey("ParksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtrasFountain", b =>
                {
                    b.HasOne("Core.Entities.Extras", null)
                        .WithMany()
                        .HasForeignKey("ExtrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Fountain", null)
                        .WithMany()
                        .HasForeignKey("FountainsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtrasLake", b =>
                {
                    b.HasOne("Core.Entities.Extras", null)
                        .WithMany()
                        .HasForeignKey("ExtrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Lake", null)
                        .WithMany()
                        .HasForeignKey("LakesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtrasLandmark", b =>
                {
                    b.HasOne("Core.Entities.Extras", null)
                        .WithMany()
                        .HasForeignKey("ExtrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Landmark", null)
                        .WithMany()
                        .HasForeignKey("LandmarksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtrasNatureReserve", b =>
                {
                    b.HasOne("Core.Entities.Extras", null)
                        .WithMany()
                        .HasForeignKey("ExtrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.NatureReserve", null)
                        .WithMany()
                        .HasForeignKey("NatureReservesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtrasPark", b =>
                {
                    b.HasOne("Core.Entities.Extras", null)
                        .WithMany()
                        .HasForeignKey("ExtrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Park", null)
                        .WithMany()
                        .HasForeignKey("ParksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ExtrasVilla", b =>
                {
                    b.HasOne("Core.Entities.Extras", null)
                        .WithMany()
                        .HasForeignKey("ExtrasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Entities.Villa", null)
                        .WithMany()
                        .HasForeignKey("VillasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Fountain", b =>
                {
                    b.HasOne("Core.Entities.Outdoor", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Fountain", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Lake", b =>
                {
                    b.HasOne("Core.Entities.Outdoor", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Lake", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Landmark", b =>
                {
                    b.HasOne("Core.Entities.Outdoor", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Landmark", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.NatureReserve", b =>
                {
                    b.HasOne("Core.Entities.Outdoor", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.NatureReserve", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Park", b =>
                {
                    b.HasOne("Core.Entities.Outdoor", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Park", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Entities.Villa", b =>
                {
                    b.HasOne("Core.Entities.Outdoor", null)
                        .WithOne()
                        .HasForeignKey("Core.Entities.Villa", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
